### ISSUE TITLE
[Question] Delay when play the song

### ISSUE THREAD

**Issue by taninsk137** [stegripe/rawon#1106]
### Describe the bug

there is a cooldown/delay when adding the song
after using "play" command
Added 1 songs to the queue
there is 5 second before it starts playing
▶ | Started playing ...

how to reduce the delay?
or is this aDurationDiff because <= 5000 in Spotify search?
sry about my English

**Comment by Mednoob** [comment]
> There is a cooldown/delay when adding the song

The delay before music start can be caused by multiple reasons, such as:
1. The internet connection of the machine used for hosting the bot is slow
2. Play-DL or YT-DLP taking a long time on fetching music stream/data
	For Play-DL, it's probably because reason 1
	For YT-DLP, it can be caused by reason 1, yt-dlp process taking long time to load, or the duration of the music/video is a bit long
3. If you're using spotify link when using `play` command. it's usually normal for it to take a bit of a long time since the bot have to fetch link data from spotify, search the song on youtube, then sort which video is suitable to be played. This process takes even longer time if you're loading a spotify playlist since the bot have to do the process for multiple times based on how many songs are there in the playlist. However, this also can be caused by reason 1 since fetching data uses internet and if the internet is slow, data fetching will also be slow.
<br />

> is this aDurationDiff because <= 5000 in Spotify search?

No, the `aDurationDiff <= 5000` is a part of our spotify search sorting algorithm (mentioned in reason 3 of music start delay) where it checks whether the video on youtube and the song on spotify having no more than 5 seconds difference in term of duration.
<br />

> How to reduce delay?

For now, I don't think there's anything you can do to reduce the delay. It's more to the process of the bot that causes this.

**Comment by taninsk137** [comment]
I host your Rawon on glitch, before upgrading to 3.1.0 (v3.0.0) play music so fast
after update to new version it has delay but less bug
