### ISSUE TITLE
[Question] No song data

### ISSUE THREAD

**Issue by zPanic** [stegripe/rawon#1118]
### Describe the bug

Similar to #1113, I'm getting this error when trying to play any YouTube link.
I have pulled the latest changes from #1116 and from the main branch, and put them in the folder, overwriting any files but leaving non-conflicting files as they were before.
However, the problem still persists.. Am I doing something wrong, or could the issue still be present?

### To Reproduce

1. Pulled latest commit
2. Restarted the bot cleanly
3. Try to play YouTube link
4. Get the error "That URL doesn't have any song data."

### Operating System

Ubuntu

**Comment by Mednoob** [comment]
Just tried it on latest commit, and it worked normally.
<div style="display: flex; flex-direction: row;">
	<img src="https://user-images.githubusercontent.com/42838410/212085821-f151448b-588e-4279-a8ca-5c9f8254f23d.png" width="400">
	<img src="https://user-images.githubusercontent.com/42838410/212085656-3065ac3f-a6f5-49d6-8e8f-0c4f07b29d32.png" width="400">
</div>

<br>
Can you send the url you used?

**Comment by Septem151** [comment]
Example URL that doesn't work: https://youtube.com/watch?v=gvaUpNDsxn0

I'm also not able to play any songs from links from YouTube. Only happens when using either Stream Handler

**Comment by Mednoob** [comment]
@Septem151 It's working normally with the url you provided

![image](https://user-images.githubusercontent.com/42838410/212522911-a9d20e99-1bc5-4fd5-9e8b-e459c628906a.png)

**Comment by Septem151** [comment]
Yeah, I don't know. It fails for every single youtube link I provide. I manually updated the code to not use the `youtubei` client provided in `src/utils/handlers/YouTubeUtil.ts` and instead using the ytdl utility function `getInfo()` found in `src/utils/handlers/YTDLUtil.ts`, but that broke search, so I updated `youtubei` to the latest version and fixed a newly introduced bug in `src/utils/handlers/general/searchTrack.ts` in which `searchRes.map()` was being called instead of `searchRes.items.map()`, and that fixed search.

So I'm not sure why this bug is occurring for some people vs others. I've tried running locally and also running in a docker container, with identical results. I've also tried logging information to the console about where an `await` function is failing to resolve, but not getting any useful data from it.

**Comment by fabriziogamboap** [comment]
Yea same on mine. When you start the bot it will work on any link, but i think if you send a lot of urls it just stops working.

**Comment by Mardaklysm** [comment]
Worked fine for me a week ago, now it doesnt anymore. I tried the latest main branch as well as the feature branches.

Every youtube link I post is stopped a few seconds later. I idnt't debug it but I assume its the no song data issue described here.

![grafik](https://user-images.githubusercontent.com/10582492/219650376-da3486ae-e7ba-44d8-b43e-911a9eca7b6f.png)

**Edit:** I tried some more urls but none worked, even those that worked before don't anymore. Interestingly the URL provided in this isuse worked: 
https://youtube.com/watch?v=gvaUpNDsxn0

**Comment by Mednoob** [comment]
Hmmm, this might be caused by rate limit (I mean, playing song often or starting the bot from a shared hosting does make you being sus'd by YT), a bug from stream handler / youtubei, or bug from youtube itself. I currently don't really know how to fix this issue since there's so little information about it.

**Comment by Mardaklysm** [comment]
I will make some tests but I doubt its a rate limit since I havent used the bot in a week and I tested some songs today and none worked. For some reason the one that got mentioned here works just fine whenever I try but I havent found a single other youtube yet that works. Soo something must be "special" to this song I assume...

Im also running the bot from my own private server. I guess I can try to switch bots later and see if that works.

**Comment by 0rdep** [comment]
@Mardaklysm try changing STREAM_STRATEGY on .env to play-dl

**Comment by mzrtamp** [comment]
> @Mardaklysm try changing STREAM_STRATEGY on .env to play-dl

This seems work for me.

**Comment by Mardaklysm** [comment]
> @Mardaklysm try changing STREAM_STRATEGY on .env to play-dl

Thank you very much, that did it. Works again now!
