### ISSUE TITLE
[Features] Skip-to command

### ISSUE THREAD

**Issue by Koooper** [stegripe/rawon#454]
Example:
!skipto 4
Result: Skipped to track 4 in queue
!skipto end
Result: Skipped to the last track in queue
!skipto start
Result: Rewinds to the first track queued

**Comment by satoufuyuki** [comment]
> Rewinds to the first track queued

It's not possible if we not save the whole track from beginning. Current queue system is removing first track if the track already done. You can't bring back old track. Wdyt? @Mednoob

**Comment by satoufuyuki** [comment]
So basically if you still want implement that, u can make queue system like groovy. Yes, they saved all tracks from beginning till disconnect. But u have to think new queue system lel

**Comment by Mednoob** [comment]
> > Rewinds to the first track queued
> 
> It's not possible if we not save the whole track from beginning. Current queue system is removing first track if the track already done. You can't bring back old track. Wdyt? @Mednoob

Actually, this is possible in disc-11 v2 because we use new queue system where we save the index of the song data. **However**, rewinding to the first track queued only possible if the loop mode set to `Queue`/`All`. If the loop mode is not set to `Queue`/`All`, rewinding to the past song in the queue is not possible.

**Comment by mzrtamp** [comment]
Doubled tracks in case

**Comment by mzrtamp** [comment]
Done in #460
