### ISSUE TITLE
[Features] Add 24/7 command

### ISSUE THREAD

**Issue by SouvikUnscripted** [stegripe/rawon#474]
Most of the music bots comes with a 24/7 command in which the bot doesn't leave the voice channel we have set, this helps in stream radios. - Thanks!

**Comment by Mednoob** [comment]
Since we're still unsure whether this will cause memory leak or not, we're going to add the 24/7 feature to the config/env so that the user can enable/disable it by themselves.

**Comment by SouvikUnscripted** [comment]
Yes, by default it will be set to disable, but if the user has a good VPS, hosting, he/she can enable it on demand. - Thanks for adding this to v2 of disc-11.

**Comment by Mednoob** [comment]
@FireUpdate 24/7 command is added. But... every time the queue is done and then you make a new queue, the state of 24/7 is reset to `disabled`. So this command have to be executed again every time you make a new queue and doesn't want the bot to leave. But don't worry, I will add `CONFIG_DEFAULT_24_7_STATE` to the config so that the user can set the default state of 24/7.

**Comment by SouvikUnscripted** [comment]
Great, thanks for adding the command, but if it gets reset every time when there is a new queue that will not make the command much useful. - But as you have told you will make default config of 24/7, that will do the work. - Thanks again!

**Comment by Mednoob** [comment]
`CONFIG_STAY_IN_VC_AFTER_FINISHED` has been added and set as default value of 24/7 feature.

**Comment by mzrtamp** [comment]
Done in #460
